### ISSUE TITLE
Série temporal - Escala gráfico

### ISSUE THREAD

**Issue by Mayara-Sakamoto** [labsid/SSDPCJ#15]
A escala vertical do gráfico poderia ser ajustada automaticamente em cada situação, para evidenciar mais as variações.
![consideracoes_escala](https://user-images.githubusercontent.com/45847979/52851658-d3378100-30fd-11e9-870d-f39f8abd7ce3.jpg)

**Comment by vialrogo** [comment]
Originalmente esse eixo era móvel, mas depois se percebeu que para dados muito planos (tipo esses dai) dava a impressão de mudanças gigantescas e se optou por eixos fixos. Eu prefiro ele fixo que da um panorama geral e o usuário faz zoom, mas eu gostaria saber que pensam os outros @carlavoltarelli, @joaotercini

**Comment by joaotercini** [comment]
Proponho voltar para eixo móvel e verificar com os usuários se atende.

**Comment by vialrogo** [comment]
@carlavoltarelli fica fácil para você modificar isso?

**Comment by Mayara-Sakamoto** [comment]
Acho que pode ser com a opção do usuário dar um zoom (podemos avaliar em conjunto). Mas essa opção também não existe atualmente (só é possível dar zoom no eixo horizontal).

**Comment by vialrogo** [comment]
@Mayara-Sakamoto foi feito o zoom e implementado no servidor de testes. Olha se fica bom assim. Por enquanto ele aparece normal, mas o quadrado do zoom pode também faz zoom vertical.

**Comment by Mayara-Sakamoto** [comment]
Acho que ficou bom.
