### ISSUE TITLE
IP Rede

### ISSUE THREAD

**Issue by Mayara-Sakamoto** [labsid/SSDPCJ#23]
O Simepar criou a API para disponibilizar as previsões para os três pontos de controle do projeto.
@vialrogo, preciso passar o IP da Rede para eles.

**Comment by vialrogo** [comment]
Oi @Mayara-Sakamoto, IPs para usar a API? Bom, são várias. Para garantir o acesso completo seriam:

IP Labsid:   143.107.167.191
LinuxDEV:  18.244.161.214
WinDev:     3.17.47.77
LinuxProd:  191.234.185.219
WinProd:    104.41.0.34

Eu não tenho certeza se vamos precisar acesso nas máquinas windows. O que podemos fazer é passar para eles a IP do Labsid por enquanto e esperar para pedir as outras quanto tivermos já algum software para consumir esses dados.

**Comment by Mayara-Sakamoto** [comment]
@vialrogo Passei somente a IP LabSid. Aviso se me notificarem quanto à disponibilização do acesso. Por favor, me avisem caso dê algum problema, ou precisar de mais alguma coisa.

**Comment by Mayara-Sakamoto** [comment]
@vialrogo @joaotercini 
Link disponibilizado: simepar.br/pcj_api
