### ISSUE TITLE
Déficits municipais

### ISSUE THREAD

**Issue by diogopedrozo** [labsid/SSDPCJ#25]
Em função da alteração/correção feita diante do défcit identificado, no município de Campinas onde algumas ETAs não captavam água mesmo havendo disponibilidade na AC, em simulações em série histórica  (issue #19), a empresa notou alterações nos déficits de outros municípios. 

Questionam se esses falhas deveriam ocorrer em outros municípios.

A empresa Rhama está analisando com mais cuidado estes dados dos déficits (eles ainda estão analisando). Segue alguns comparativos feito por eles 
Atibaia: Média de déficit anterior: 0,012 m³/s - Média de déficit novo: 0,014 m³/s
Bragança Paulista: Média de déficit anterior: 0,001 m³/s - Média de déficit novo: 0,000 m³/s
Cosmópolis: Média de déficit anterior: 0,113 m³/s - Média de déficit novo: 0,112 m³/s
Sumaré: Média de déficit anterior: 0,004 m³/s - Média de déficit novo: 0,000 m³/s
Hortolândia: Média de déficit anterior: 0,003 m³/s - Média de déficit novo: 0,000 m³/s
Itatiba: Média de déficit anterior: 0,015 m³/s - Média de déficit novo: 0,014 m³/s
Jundiaí: Média de déficit anterior: 0,052 m³/s - Média de déficit novo: 0,047 m³/s

De acordo com a solução apresentada no issue #19 o erro nas captações, que ocasionava déficit nos municípios, quando ETAs não captavam água mesmo havendo disponibilidade, o problema estava relacionado ao índice de perdas com 3 casas decimais. Sendo esse corrigido, o impacto seria para todos os municípios, o que geraria alteração geral, correto? 
Por isso a variação identificada nesses outros municípios?

**Comment by diogopedrozo** [comment]
@joaotercini Estava avaliando esses municípios e notei que permanece a questão do issue #19 , como no município de Atibaia, onde as ETAs captam na ATIB095 e aparentemente há vazão disponível (na série nunca chega a zero a vazão no trecho) e não estão captando, gerando déficit no município.
Pelo BD olhei se haveriam demandas a montante ou a jusante com prioridade maior ou até igual (que disputasse a vazão) e existe com prioridade maior apenas o ponto de controle, mas que lança 100% ainda a montante do ponto de captação do município. As outras vazões somadas não chegam ao limite da disponível na AC na série.

**Comment by labsid** [comment]
@diogopedrozo qual cenário você está rodando? 
O cenário 2208 não apresenta essas características. Apensa o município de Cosmópolis tem 0,9 de déficit que é uma restrição da ETA que está fornecendo o máximo 0,167 e não um bug.

**Comment by joaotercini** [comment]
@diogopedrozo qual cenário você está rodando?
O cenário 2208 não apresenta essas características. Apensa o município de Cosmópolis tem 0,9 de déficit que é uma restrição da ETA que está fornecendo o máximo 0,167 e não um bug.

**Comment by diogopedrozo** [comment]
Rodei o cenário 2199, um cenário de teste que criei para Série Histórica, com base no cenário 2194 da PROFILL. Já fiz uma série de modificações para testar, mas inicialmente foi criado com base nesse 2194, então se for viável, criar outro com base nesse para avaliar.

**Comment by joaotercini** [comment]
Entendi agora o que está dizendo, sim a falha acontecia no geral, para todos os municípios que tinham perdas com mais de 2 casas decimais.
Mas os resultados estão ok! Podemos partir para as conclusões
Observe o município de Jundiaí que tem a principal ETA na JUNA168.

![image](https://user-images.githubusercontent.com/30443464/53352018-d3572e00-3900-11e9-8e42-79b93d889af8.png)

Apesar da média ser 0,047 m³/s não quer dizer que o tempo todo faltou água para o município, os déficits aparecem quando falta água no rio e tem meses com magnitude de 50% da demanda.
