### ISSUE TITLE
Documentar alterações recentes no SSD

### ISSUE THREAD

**Issue by diogopedrozo** [labsid/SSDPCJ#26]
Em virtude das recentes modificações realizadas no SSD foram percebidas por parte da empresa que está revisando o Plano de Bacias mudanças em diversos resultados da modelagem, tanto para qualidade, quando para quantidade.

Quanto à qualidade foi notado impactos significativos na calibração de Nitrogênio e Fósforo, sendo este último fortemente alterado. Isto exigirá a recalibração destes parâmetros e posterior revisão dos resultados e tabelas já elaboradas e, assim, buscam saber o que foi alterado e como estava antes, para ter documentadas as alterações. Esta documentação é importante também para poderem dimensionar e corretamente direcionar o caminho da re-calibração e da nova análise dos resultados.

Dentre as modificações feitas responder sobre:

1) Todas as alterações feitas no SSD;
2) Impactos dos percentuais na truncagem dos valores em duas casas decimais. Isto foi feito para todas as variáveis (vazão e qualidade)? Sobre este ponto, nota-se que algumas ETEs pequenas ficaram sem vazão tratada e também que alguns municípios deixaram de distribuir 100% do esgoto entre as ETEs em função da supressão destas menores. Assim precisam definir bem qual caminho tomar para corrigir esta questão. 
3) Nas ETEs, foi feita alguma mudança nos nomes das ETEs? A alteração nos nomes impacta nos procvs. Se foram feitas alterações, quais?

**Comment by vialrogo** [comment]
Oi Diogo, esta é um discussão que vai ser um pouco mais comprida. Primeiro, não temos como responder "Todas as alterações feitas no SSD", o SSD é um sistema muito complexo, todas as alterações é uma coisa bem, bem grande. Mas posso te falar sobre as mudanças feitas ao respeito das perguntas que eles fizeram. 

De fato tem uma mudança nos dados de qualidade. Com base nos testes do fósforo foi encontrado um erro em um if, o que fez com que umas contas estivessem sendo mal feitas para um tipo específico de simulações. @joaotercini pode esclarecer mais um pouco se necessário já que ele implementou a correção. Esta é a mudança importante já que vão ter que se refazer sim algumas simulações.

Com respeito aos porcentuais troncados, não tem como calcular o impacto da truncagem, teria que ir cenário por cenário para fazer. Foi definido que o sistema aceita duas casas decimais e para duas ele funciona bem, mas eles insistiram em botar mais. O que a gente fez foi forçar internamente para ser duas, assim o garantimos que a simulação funciona. Mas não, aqui o problema não é de sistema e sim de usuário. Tem que se usar duas casas decimais só como já foi falado.

A única mudança dos nomes das ETEs que foi feita foi tirar um `'` de um nome, imagino que isso não tem impacto algum.

**Comment by diogopedrozo** [comment]
> Oi Diogo, esta é um discussão que vai ser um pouco mais comprida. Primeiro, não temos como responder "Todas as alterações feitas no SSD", o SSD é um sistema muito complexo, todas as alterações é uma coisa bem, bem grande. Mas posso te falar sobre as mudanças feitas ao respeito das perguntas que eles fizeram.
> 
> De fato tem uma mudança nos dados de qualidade. Com base nos testes do fósforo foi encontrado um erro em um if, o que fez com que umas contas estivessem sendo mal feitas para um tipo específico de simulações. @joaotercini pode esclarecer mais um pouco se necessário já que ele implementou a correção. Esta é a mudança importante já que vão ter que se refazer sim algumas simulações.
> 
> Com respeito aos porcentuais troncados, não tem como calcular o impacto da truncagem, teria que ir cenário por cenário para fazer. Foi definido que o sistema aceita duas casas decimais e para duas ele funciona bem, mas eles insistiram em botar mais. O que a gente fez foi forçar internamente para ser duas, assim o garantimos que a simulação funciona. Mas não, aqui o problema não é de sistema e sim de usuário. Tem que se usar duas casas decimais só como já foi falado.
> 
> A única mudança dos nomes das ETEs que foi feita foi tirar um `'` de um nome, imagino que isso não tem impacto algum.

**Comment by diogopedrozo** [comment]
Boa tarde Victor.

Acredito que as alterações a que eles se referem são as efetuadas nos últimos dias, que realmente impactaram nos resultados (ou no ajuste para obter os resultados corretos), exatamente nesses pontos que você colocou. Mas podemos tentar levantar qual exatamente são os pontos que eles gostariam de saber, e que diante da complexidade do SSD não há como apontar TODAS as alterações.

Não vou responder pontualmente os questionamentos ainda, pois há necessidade de um alinhamento interno e gerencial (Léo e Sidnei) dos próximos passos diante dos ajustes que impactam na calibração, na parcela de esgoto nas ETEs (será necessário balancear o percentual do esgoto nos municípios para chegar a 100% e ver a solução que irá se dar para as ETEs menores que passaram a  não receber esgoto), a questão dos nomes das ETEs que eles usam em tabelas (que vamos precisar frisar que existe os IDs como referência para todos aspectos - Município, ETE, ETA, Cenário, Reservatório...., que é isso que deveriam usar para fazer os PROCVs que mencionam).

De qualquer forma, quando a agência for alinhar todos os pontos com eles, precisaremos "documentar" esses pontos comentados. Esclarecer de forma clara o que causava os erros e como foram solucionados.

**Comment by vialrogo** [comment]
Sim, concordo. Mas com respeito as ETEs é o que te falei. Porque não da 100%? Imagina este caso, eu boto 3 ETEs, com parcelas de 0.333333333 cada uma. O sistema vai arredondar cada para 0.33, mas 0.33*3 = 0.99 não a 1. Ai que está o problema. O certo seria fazer as ETEs com valores de 0.33, 0.33 e 0.34 para a soma dar 1.

Em termos gerais, todas as mudanças feitas sempre são registradas nos relatórios, na seção de atendimento a requisições. Mas para o detalhe exato de o que foi feito só no código. Agora que usamos os Issues também podem ser uma ferramenta para ver as mudanças.

**Comment by vialrogo** [comment]
Vou fechar o issue já que não temos nada para fazer nele realmente, mas se quiser a conversa pode continuar aqui, mesmo fechado.
