### ISSUE TITLE
Demanda XML

### ISSUE THREAD

**Issue by diogopedrozo** [labsid/SSDPCJ#27]
Constatei observando os resultado XML comparando com resultado da interface que algumas demandas não estão aparecendo no XML.
Exemplo.
Demanda na AC JUND168
![image](https://user-images.githubusercontent.com/47661039/53122826-645f8b00-3536-11e9-907f-9a995313b6d6.png)
![image](https://user-images.githubusercontent.com/47661039/53122612-bfdd4900-3535-11e9-9505-e2bcb78a99c0.png)

Demanda AC226
![image](https://user-images.githubusercontent.com/47661039/53122727-1185d380-3536-11e9-94ab-cab9b0572da9.png)
![image](https://user-images.githubusercontent.com/47661039/53122736-18144b00-3536-11e9-829e-fbef92c553fc.png)

**Comment by joaotercini** [comment]
Encontrei o erro, ele está colocando na tabela só as demandas que tem **captação superficial** e **lançamento** pra não ter dado nulo na tabela. No primeiro exemplo a demanda da JUNA168 é a "Estimada332" ela é consultiva, não tem retorno, na hora de preencher o XML vou programar pra coluna AC_Lancamento vir nula.
